### ISSUE TITLE
Option to re-prompt for password or d-pad pin entry during startup

### ISSUE THREAD

**Issue by hashnag** [jellyfin/jellyfin-androidtv#1080]
**Describe the feature you'd like**	
Would love to see options to re-prompt for password or d-pad pin entry during startup similar to Jellyfin 11.x series.

**Additional context**	
12.x series seems to have adopted a token-based logon feature that bypasses the need to authenticate each time you log in. This is no doubt super convenient for many use cases. However having a multi-user household with a great range of different age groups (3, 12, 15, and OLD) some of us rely on the requiring log on to keep adult accounts separate.

Pervious versions used server-side settings to determine which accounts require password (or pin) entry, which accounts do not require password entry, and which accounts do/do not display on the login screen. Similar options if possible would be very much appreciated.

Thanks for all your hard work!

**Comment by nextlooper42** [comment]
Can someone remove tag enhancement and put critical bug instead? Basically unsafe to have this new version installed in household with kids and use Jellyfin for movies that are not cartoons. Since they can log for example my account and watch John Wick instead...

At least Jellyfin could forgot the pin every time :(

**Comment by nielsvanvelzen** [comment]
> Can someone remove tag enhancement and put critical bug instead?

No, this is not a critical bug.
