### ISSUE TITLE
Sort by star rating sorts wrong (All Items / grid view)

### ISSUE THREAD

**Issue by JannikHoelling** [jellyfin/jellyfin-androidtv#1135]
**Describe the bug**
When i sort movies on the grid layout by rating(star rating) they are not sorted correctly. The first movies are sorted like this: 6.4, 8.0, 8.1, 8.1, 8.5, 6.4 and it goes on randomly sorted. I can't see any system in the sorting there. The sorting is the same everytime i refresh.  

Ciritic rating actually works like expected and is sorting correctly.

**To Reproduce**

1. Go to a Tv Show or Movie library
2. Go to "All Items"(Grid layout view)
3. Click on the sort option in the top right corner (AZ)
3. Select "Rating"
4. Movies will not be correctly sorted

**Expected behavior**
Movies should be sorted by their rating. In the example above the 8.5 Movie should appear before the 6.4 one.

**Logs**
No error logs available

**Screenshots**
https://imgur.com/a/XFiSj0J

**System (please complete the following information):**
 - Android TV version: v0.12.0-beta.6
 - Device manufacturer: TCL
 - Device model: TCL U49P6046
 - Jellyfin server version: 10.7.7

**Comment by nielsvanvelzen** [comment]
The sorting works as "intended" although it might look broken because the value of the field used for sorting is not shown for the movies:

- The "Rating" sort option uses the OfficialRating field
- The rating shown with a star is the CommunityRating field
- The rating shown with a tomato is the CriticRating field

So the order is not obvious for you because the sorting uses a field that is not shown.
