### ISSUE TITLE
Player select libVLC, playback time display is wrong, subtitles and audio tracks are not displayed.

### ISSUE THREAD

**Issue by shaino** [jellyfin/jellyfin-androidtv#1147]
**Describe the bug**

Web playback time display is wrong:
Continue playing after selecting chapters and sections, and the time will change to 00:00:00.

Subtitles and audio tracks are not displayed:
There is no check mark when opening subtitle and track options.
The default flag caption will not be displayed initially, and no caption will be displayed when any caption mode is selected in the user control panel.
When multiple subtitles and tracks are selected, if subtitles are selected first and then tracks are selected, the track selection will be ignored. Subtitles must be selected again for the selected track to be valid.

**To Reproduce**
1. Video player type selection: libVLC.
2. Select a chapter or drag the time bar.
3. Select subtitles or tracks.

**Expected behavior**
Available as Android. There are no such problems with Android apps on the same server.

**Logs**
Not yet.

**Screenshots**
Not yet.

**System (please complete the following information):**
 - Android TV or Fire TV version: Android 9
 - Device manufacturer: Xiaomi
 - Device model: 6
 - Jellyfin server version: 10.7.6/10.7.7

**Additional context**
Not yet.

**Comment by MovieWiz** [comment]
The aspect ratio tool also appears to be missing when using vlcLib as the player.  I had a 4:3 video playing in stretched mode and there was no way to change it.  I know this is still a beta.  Just letting you know that, at the moment, when playing to a standard stereo TV using my Android TV box, there are currently no good choices for direct play.  Exoplayer can't play the AC3 5.1 -- it must be transcoded.  While vlcLib can decode and downmix the AC3 5.1, there is no way to adjust the aspect ratio.  I know -- life is hard :-)   ...  just trying to be helpful since this is such a great application.

**Comment by satstarter** [comment]
I have the same problem as MovieWiz but i managed to get rit of the black background for the srt subs and also smaller textsize
in exoplayer i found this here on the site so i changed the code and compiled but this code was for exoplayer where can i find this for libvlc please thanx in advance ps: i love jellyfin and thanx for the work you guys do but for now for me its better to play my files with kodi
