### ISSUE TITLE
Cannot Publish on Play Store

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin-androidtv#117]
Currently getting this message:

> Warning
> This release is not compliant with the Google Play 64-bit requirement
> 
> The following APKs or App Bundles are available to 64-bit devices, but they only have 32-bit native code: 900.
> 
> From August 1, 2019 all releases must be compliant with the Google Play 64-bit requirement.
> 
> Include 64-bit and 32-bit native code in your app. Use the Android App Bundle publishing format to automatically ensure that each device architecture receives only the native code it needs. This avoids increasing the overall size of your app.

**Comment by thornbill** [comment]
This is due to the libvlc jar included in this repository only being built for ARM 32-bit. We should migrate to the official builds available [here](https://bintray.com/videolan/Android/LibVLC-Android). We need to migrate to androidx to use these builds and fix incompatibilities between libvlc 3.0.x that is currently in use and 3.1.x available there.

**Comment by anthonylavado** [comment]
@thornbill Apprived AndroidX change.

**Comment by thornbill** [comment]
#121 should add support for x86 and 64-bit architectures.
