### ISSUE TITLE
Audio track and subtitles settings reset after TV goes to screen saver

### ISSUE THREAD

**Issue by lsrom** [jellyfin/jellyfin-androidtv#1198]
### Describe the bug

1. Play movie/show episode
2. Change subtitles/audio track from default to any other
3. Pause and wait for TV to go to screen saver
4. Resume playback - subtitles and audio track reset to default

### Application version

0.12.0

### Device information

Nvidia Shield 2019

### Android version

8.2.3

### Jellyfin server version

10.7.7

**Comment by mueslimak3r** [comment]
When I test this with subtitles I can reproduce the UI setting for subtitles resetting to default. For me that's going back to "none" being checked. But the subtitles themselves remain. Is that consistent with what you're experiencing? Or does both the UI setting and the actual subtitles displayed get reset?

**Comment by MaximeLussier** [comment]
I have the same issue. When stopping a video, if the selected audio track is not the default, when I resume, the default is played instead of the selected track.
I tested with the web-ui and it has the correct behavior.
This is with the latest release on an NVidia Shield Pro

**Comment by mueslimak3r** [comment]
> When stopping a video

To clarify, by "stopping" does that mean:
* Exiting the player and then clicking "resume from"
* Pausing the video and letting the screensaver come on

**Comment by MaximeLussier** [comment]
I thought it was both, however, i just tried the first and it was correct.
The screensaver seems to be required. I will test again tomorrow.

On another note...
I've also been seeing another issue which may be related, however, I have not been able to characterize it enough yet.
I believe that when the screensaver comes on while the Jellyfin App is active (instead of the Google TV home) and my receiver is off. When I re-start my receiver, the Shield Tv has no sound output, I need to reboot it to recover. Like I said, I haven't characterized it yet and I do not know if it is really related to the Jellyfin App yet. I will open an issue if I find out more... It seems to break the sound for the entire device...
