### ISSUE TITLE
Pressing Settings on remote will turn off playback and results in black screen

### ISSUE THREAD

**Issue by Aealo** [jellyfin/jellyfin-androidtv#122]
Hello,
I have started using Jellyfin for my Phillips Android TV and I have noticed that when I press settings button on my remote during playback, it will be stopped and TV will show settings overlay over black screen. Pressing back button on remote will do nothing and the only way to continue using TV is to press Home to get back to Android homescreen. When using other apps like netflix/emby/plex and pressing settings button the playback will pause and overlay will be shown over movie. Can this be fixed? Thanks

**Comment by anthonylavado** [comment]
@thornbill Don’t know what your take on this is. Enhancement or bug?

**Comment by thornbill** [comment]
This seems like a bug. I don't have a way to replicate this exactly and it doesn't seem like there is a way to bring up the settings in this fashion in an emulator, but I was able to cause a similar crash in the emulator by bringing up the task switcher (square button) while playing a movie. Perhaps the fix for it will fix this issue also. :crossed_fingers:

**Comment by LeoVerto** [comment]
I've also had this issue and can confirm that #123 fixes it.

**Comment by LeoVerto** [comment]
Fixed in v0.9.1.
