### ISSUE TITLE
Opus & HEVC Support Not Detected Properly

### ISSUE THREAD

**Issue by Protektor-Desura** [jellyfin/jellyfin-androidtv#1305]
### Describe the bug

I just reinstalled Jellyfin 10.7.7 on Docker and it is not properly detecting the capabilities of the Amazon Firestick 4K. It reports that it needs to transcode the audio when it is Opus. That is incorrect. The Amazon Firestick 4K supports Opus up to 8 channels. It gets this error when the Exoplayer is used but not the LibVLC player.

https://developer.amazon.com/docs/fire-tv/device-specifications-fire-tv-streaming-media-player.html?v=ftvstick4k

Android by default does support Opus audio.

https://developer.android.com/guide/topics/media/media-formats

I should mention that it is also transcoding HEVC to H.264 which it shouldn't need to do either. Also the MKV container is supported as well, even though it is outputting a MP4 file instead.

### Application version

0.12.3

### Device information

Amazon Firestick 4K

### Android version

Firestick OS 6.2.8.1 (NS6281/4061)

### Jellyfin server version

10.7.7

**Comment by michaelkrieger** [comment]
Can echo this.  Also seeing

hevc (native) -> h264 (h264_vaapi)
dts (dca) -> ac3 (native)
and the container also indicating it is not supported.


Seeing this with a HEVC Main 10 video, and audio streams of (TrueHD 7.1, DTS-HD 7.1, and AC3 5.1).
Given the odd transcode, the video sputters every once in a while because of the mostly unnecessary transcode.
Jellyfin should simply be supplying it the native HEVC video stream and the AC3 audio stream if it's not supported.

**Comment by jcdick1** [comment]
I can confirm, as well.  Video in VP9+Opus 5.1 transcodes to h264 and AC3 on the Amazon Fire TV (3rd Gen) dongle.
