### ISSUE TITLE
AV1 not playing with libVLC player

### ISSUE THREAD

**Issue by Protektor-Desura** [jellyfin/jellyfin-androidtv#1306]
### Describe the bug

I want to report that that when libLVC is used as the player it reports to Jellyfin that it can play AV1 video codec but all I get is a black screen like it can't actually play AV1 video. I hear the audio and see the subtitles but get a black/blank screen for video.

Is AV1 support not compiled in the libVLC player?

### Application version

0.12.3

### Device information

Amazon Firestick 4K

### Android version

Firestick OS 6.2.8.1 (NS6281/4061)

### Jellyfin server version

10.7.7

**Comment by mueslimak3r** [comment]
Can you try the latest beta and see if that fixes it? If not, it may be because the version of libVLC that's used is a couple versions behind.

If you want to build it yourself and see if a fix is as simple as upgrading the library, change the version # in this file then do a gradle sync
https://github.com/jellyfin/jellyfin-androidtv/blob/master/gradle/libs.versions.toml
