### ISSUE TITLE
Coonecting or disconnecting a bluetooth keyboard stop playback

### ISSUE THREAD

**Issue by Arial-Z** [jellyfin/jellyfin-androidtv#1486]
### Describe the bug

Start playback
Connect or disconnect a bluetooth keyboard (only tested with a keyboard)
Playback stop

playback should continue when a bluetooth device get connected or disconneted as most of them have a idle disconnect / power off

Maybe related to [#1061](https://github.com/jellyfin/jellyfin-androidtv/issues/1061)

[adb.log](https://github.com/jellyfin/jellyfin-androidtv/files/8180118/adb.log)

### Application version

0.13.0-beta.4

### Device information

Nvidia Shield Pro 2019

### Android version

Android 11

### Jellyfin server version

10.7.7

**Comment by mueslimak3r** [comment]
Does the system play a sound when you connect/disconnect the keyboard?

If so, it's likely the audio focus loss that stops playback. Currently we don't handle transient audio focus loss and allow playback to pause then resume if focus is regained quickly.

**Comment by Arial-Z** [comment]
No sound just playback stop and jellyfin go back to the library panel with error "Aucun élément à lire" should translate to something like "No media to play"
Bluetooth disconnect around line 1000
[adb bluetooth.log](https://github.com/jellyfin/jellyfin-androidtv/files/8217077/adb.bluetooth.log)

**Comment by ACR-Jeff** [comment]
I have the same exact issue. 
I have a Rii Mini i8+ keyboard that I use with my android tv box. It connects using bluetooth, 
If I choose any of the built in player options "Automatically choose, ExoPlayer and LibVLC", When playing a video with either of those three options selected in the player preferences. While playing a video then flip the off button on my bluetooth keyboard the player will close instantly and go right back to the video details screen. 

I know it's not a device issue because I have played with this for some time now, I have tried other players "VLC media player, MX Player and etc." Every external player works fine within Jellyfin and outside of Jellyfin.
Only happens with the built in media players within Jellyfin.

**Comment by mueslimak3r** [comment]
Assuming the issue is related to audio focus, it's likely that a fix won't come until the playback rewrite is ready. Prior to the rewrite, I fix would require a non-trivial redesign anyway to get things functional. The reason being that using media sessions is the right way to properly handle the variety of playback interrupting events that may occur.

@ACR-Jeff the log you provided doesn't show any log output from the jellyfin app. If you could re-record it then I'll check again. With logs we may find a fix is feasible right away.

**Comment by ACR-Jeff** [comment]
Oh sorry about that. I am used to doing it on a different device, I believe I have it figured out now. Hope this helps solve this issue. Thank you
[logcat.txt](https://github.com/jellyfin/jellyfin-androidtv/files/8260522/logcat.txt)

**Comment by mueslimak3r** [comment]
> Oh sorry about that. I am used to doing it on a different device, I believe I have it figured out now. Hope this helps solve this issue. Thank you
> 
> I went through each player two different times to make sure the logs caught everything as best as possible. Hope this helps. [logcat.txt](https://github.com/jellyfin/jellyfin-androidtv/files/8260522/logcat.txt)

From those logs it does look like the issue is caused by losing audio focus.

**Comment by odin81** [comment]
I'm facing the same problem.
When the bluetooth keybord get's disconnected after about 30 minutes, jellyfin restarts.

**Comment by jadev-projects** [comment]
I have the same problem when my keyboard disconnects itself or when I switch it off. It's very annoying, and the alternative I've found is to download the application on my cell phone that lets me control the box like a remote control.
I hope that the community will be able to solve this problem, as the player recovers the event and returns to the film description, which shouldn't happen.
Perhaps by being more rigorous about the events used to stop a video, the problem will resolve itself.
I hope this problem will no longer be ignored.
