### ISSUE TITLE
FireTV Playback Issues with v0.13 on both libVLC and Exoplayer

### ISSUE THREAD

**Issue by wickedfable** [jellyfin/jellyfin-androidtv#1554]
### Describe the bug

After updating to the later version of Jellyfin on my FireTV Cube, I started experiencing playback issues through both libVLC and Exoplayer. With Exoplayer, videos quickly start stuttering randomly as if there's a buffering issue. The playback will pause for a brief moment at random before continuing to play and then repeat the cycle every couple of seconds or so. On switching to libVLC, the playback is smooth but I am unable to change audio tracks, fast forwarding/rewinding doesn't work with .TS files (it shows the progress bar moving but it resets to the beginning of the video), as well as chapter selection being impossible (similarly just starts from the beginning). 

I went back to the previous version v0.12.3 version and everything works as expected there.

To replicate: The Jellyfin server version I am on is 10.7.6 and I am accessing the app on a FireTV Cube with Fire OS 7.2.4.2. It seems like all videos are affected by these issues. 

### Application version

0.13.0

### Device information

Amazon FireTV Cube 2nd Gen

### Android version

Fire OS 7.2.4.2

### Jellyfin server version

10.7.6

**Comment by DavidFair** [comment]
We need the logs from 0.12.3 and 0.13 to help us see a difference in how the video is being transported. It could be a number of things from it:
- Now Remuxing
- Transcoding when it shouldn't
- Not transcoding anymore when it did previously
- Something unrelated

But there's no way to eliminate any of these without logs.


My hunch (and this is wild speculation) is that the .ts file is being processed in chunks. Previously 0.12.3 forced unnecessary transcoding which "fixed up" the container from chunks into a single continuous stream. 
Since detection of direct play is improved we're now playing those chunks directly, causing Exoplayer to grab each chunk as a separate request which causes hitches and preventing VLC from seeking to keyframes that don't exist. (I've seen the latter with VLC and .ts files on a desktop machine so it's potentially not a Jellyfin bug)

**Comment by wickedfable** [comment]
I'll try to grab the logs once I have access to the device again (I'm currently away from it), but I did want to mention that the weird stuttering/buffering issue is happening with several different video file types when using Exoplayer, not just .ts. The .ts just also had some specific issues with not being able to rewind, fast forward, or select chapters under libVLC. But everything, including .ts files played smoothly on libVLC, otherwise.

On going back to 0.12.3, everything works as normal with being able to change audio tracks, rewing/fast forward, and no stuttering/buffering issue on all video files.

**Comment by mueslimak3r** [comment]
Can you try side loading the 0.13-beta2 APK and see if it still stutters/stops to buffer frequently

**Comment by wickedfable** [comment]
I didn't realize it's a little more work to get the logs from the AndroidTV version, so I haven't had a chance to do that yet, but I did test out the 0.13-beta2 APK.

It has similar stuttering/buffering issues though it seems like to a lesser degree potentially. I didn't get a chance to test as wide a variety of videos as I did the first time but the same issues were popping up with the few videos I did test. Some were able to play for a lot longer before they would stutter/buffer though.

**Comment by mueslimak3r** [comment]
Does this happen when direct playing, transcoding, or both. Can you provide the ffmpeg logs from your server if it happens when transcoding? To get a useful ffmpeg log, make sure to get the latest one right after testing playback on your fire TV cube
