### ISSUE TITLE
0.13.2 Jellyfin client not available in firetv app store.  Unable to locate in appstore search. 

### ISSUE THREAD

**Issue by junobomb** [jellyfin/jellyfin-androidtv#1561]
### Describe the bug

Not really a bug, but currently cannot find the published download for the app in firetv app store.  Search results do not find Jellyfin.

### Application version

0.13.2

### Where did you install the app from?

Amazon Appstore

### Device information

FireStick 4k Max

### Android version

FireOS 7

### Jellyfin server version

10.7.7

**Comment by TheHellSite** [comment]
Can confirm, same issue here. Fire TV Stick 2nd gen

**Comment by mueslimak3r** [comment]
I accidentally hit the lock button, sorry.

There was an issue with Amazon approving the latest update, and I assume that's why it isn't showing up.

It will be resubmitted so hopefully it won't take too long to show up again in the Amazon app store

**Comment by junobomb** [comment]
Cool thanks for filling me in. Its so weird, the Jellyfin icon has since disappeared on all my firetv's. Still opens up, but its just a gray box now.

**Comment by nielsvanvelzen** [comment]
It's unfortunate that Amazon hides the app after an update failed a review but we can't do much about that. I've pinned the issue for visibility and we'll post an update here once the issue is resolved.

**Comment by jcdick1** [comment]
I'm still getting QuasiTV as a result searching for Jellyfin on my 4k Max stick, and the Amazon.com appstore webpage is still saying the app is incompatible.

**Comment by nielsvanvelzen** [comment]
@MovieWiz I'm glad the issue is resolved for you, can you check what version you currently have installed (you can see that in the app settings).

On our side it still looks like not everything is resolved. Amazon is still evaluating our resubmission and the store lists the app as incompatible with a lot of devices.

**Comment by MovieWiz** [comment]
I have 0.13.2 installed on FireTV Stick Lite (2020) and FireTV Stick 4K.  I originally installed from the package that I downloaded.  When I did the context menu on the Jellyfin icon, I would choose "More Info" and it would take me to the store page where it would say the app is Unavailable.  Eventually the icon turned gray as well, as others reported.

After clearing the AppStore's data, the store page now says "Open" rather than "Unavailable".  And I have the standard blue Jellyfin icon again.

Note that I have not tried searching for the Jellyfin app.  It's possible that might take time -- maybe the app store is only indexed periodically.  Or maybe that part just doesn't work yet.

But it does appear to be there in the appstore and the page indicates that it is 0.13.2.

But this will be of little value if no one can find the app in the appstore.  I suspect very few people download the package and install it on FIreSticks like I did.

**Comment by sdoan99** [comment]
verifying jellyfin is still not on the appstore

**Comment by MovieWiz** [comment]
Yes, when I get the app's store page (using the "more info" method described in my previous post), it is back to having a status of "Unavailable".  Searching for Jellyfin on my Fire Stick does not find it.  Oddly, if I search for Jellyfin on the amazon site in the browser on my PC, I find "Jellyfin For Fire TV" no problem.

Note that if you're signed into the Amazon account on which your Fire Stick is registered, you can initiate an install to the desired Fire Stick from the app's page in the browser -- something I didn't know but noticed today.

**Comment by jcdick1** [comment]
It's now showing up on my 4k Max, so hopefully its resolved for more people.

**Comment by nevado** [comment]
Fixed for me this morning, able to view the app in appstore again and updated from 0.13.0 to 0.13.2. Fire Stick 4k

**Comment by spidercoat** [comment]
UK Fire TV stick user  (2nd Gen) here...
The app is not in the app store, although it would appear _something_ may have happened because a search no longer brings up "QuasiTV" bizarrely.

**Comment by nielsvanvelzen** [comment]
We've just been notified by Amazon that the app should be live again. I'm unable to verify it right now so let me know is the app is still unavailable.

**Comment by lukeeexd** [comment]
I can confirm it is there now

**Comment by spidercoat** [comment]
Also now available on 2nd Gen Firestick. Downloaded easily and worked without issue. :+1:

**Comment by thornbill** [comment]
I have confirmed the app is listed as available for all of my devices now. Let us know if you have any further issues! :purple_heart:

**Comment by nielsvanvelzen** [comment]
Amazon once again denied an app update so they delisted the app again. We're working on it but it all depends on Amazon.

**Comment by nielsvanvelzen** [comment]
App is available again!

**Comment by sirEgghead** [comment]
For me, it shows up under my search results, but when I click on it, it says "App not found", so I am unable to install it.

**Comment by mueslimak3r** [comment]
> For me, it shows up under my search results, but when I click on it, it says "App not found", so I am unable to install it.

Which Amazon device do you have, including the specific year/generation?
eg: Fire Stick 1st Gen/2014

**Comment by sirEgghead** [comment]
> > For me, it shows up under my search results, but when I click on it, it says "App not found", so I am unable to install it.
> 
> Which Amazon device do you have, including the specific year/generation? eg: Fire Stick 1st Gen/2014

Sorry, I never got a notification for this.  It's a first year stick, but I don't remember the purchase year.  I'll have to check when I get back home.  It's time for an upgrade though.
