### ISSUE TITLE
Transcode flac to MP3

### ISSUE THREAD

**Issue by 97carmine** [jellyfin/jellyfin-androidtv#163]
Tested on a Xiaomi TV Box S

The songs in flac format automatically transcode to 128 Kbps mp3.

The playback of .flac songs are played without transcoding in the Android app.

**Comment by vi-n** [comment]
I've started to look into this, and it seems it's happening in the following code block (from jellyfin-androidtv/app/src/main/java/org/jellyfin/androidtv/model/compat/StreamBuilder.java):

`            Integer tempVar4 = options.getAudioTranscodingBitrate();
            Integer tempVar5 = options.getProfile().getMusicStreamingTranscodingBitrate();
            int transcodingBitrate = (tempVar4 != null) ? tempVar4 : (tempVar5 != null) ? tempVar5 : 128000;`

The profile seems to refer to the dlna profile, which is set to 128000. I am unsure if the dlna profile makes sense to use in the AndroidTV code? I know to little of the app.
The function `getAudioTranscodingBitrate()` will always return `null` as far as I can tell because the setter is never called. For my use case (and I pressume the usecase of the other two people in this thread) would prefer the default be "unlimited" or direct play. 

When I find the time I will try to see and make that work.

**Comment by thornbill** [comment]
The issue here seems to be that ExoPlayer does not support playing flac without using an extension. More recent versions of the ExoMedia library include the extensions by default, but we are still using a quite old version.

We could potentially use libvlc since it should direct play flac and we already use it to play some video formats and use it by default on older devices.

**Comment by AndreasGB** [comment]
My god, that file is an abomination with all those `tempVar`s. Should I add an issue that those need to be cleaned up?

**Comment by thornbill** [comment]
I wouldn't. There are **so** many files that need cleaned up that would just clutter the issue list. :joy: :sob:

**Comment by neopc10** [comment]
Anything new on this?

**Comment by MrChip53** [comment]
> Anything new on this?

From my quick test of the dev build, flac audio plays fine for me. I'd say _potentially fixed_. Haha
