### ISSUE TITLE
No audio only transcode possible?

### ISSUE THREAD

**Issue by Andy2244** [jellyfin/jellyfin-androidtv#1687]
### Describe the bug

If i play a DTS only file via Edge browser i see that the server only transcodes the audio stream. If i try the same via JellyfinTV app it always also transcodes the video.

The reason given on Shield TV is Audio channels not matching, while the user has set auto/7.1 and shield is also set to allow EAC3.
The reason should be that DTS pass-through is disabled in the player, which is stated correctly for the web version.

So there is no way to get DTS->AC3 transcoding working atm on Shield TV, without also transcoding the video?

PS: Its related to #1685 so check the logs there.

### Application version

0.13.3

### Where did you install the app from?

Google Play

### Device information

Shield TV Pro 2019

### Android version

Android 11

### Jellyfin server version

10.8.0-beta2 and 10.8.0-unstable

**Comment by tony678933** [comment]
As an added issue, not sure if relevant. When I watch TV shows on my Sony Android TV the audio will sometimes cutoff mid-stream. I noticed it's only an issue with the Android TV app since the player on a browser and android phone are perfectly fine.

I have an LG sound bar thats connected with an optical cable to the TV.

The audio for the show is reported from jellyfin as being 
English - Dolby Digital+ - Stereo
![image](https://user-images.githubusercontent.com/49970595/172033504-267d57ef-65da-417a-ba08-347cab0f7db1.png)

Please let me know if this is an audio transcoding issue.
