### ISSUE TITLE
Next Up in middle of the episode

### ISSUE THREAD

**Issue by InanZen** [jellyfin/jellyfin-androidtv#1693]
### Describe the bug

Strange bug happened to me: I was watching an episode and at midpoint (and later at 3/4 point) the episode playback paused and Next Up screen popped up trying to automatically switch to the next episode. 
This happened on two subsequent episodes (ep. 3 and 4), while previous episodes played normally.
I've than set the setting Playback -> Show next video info -> Never, which may or may not have fixed it, (it might be that just those two episodes were bugged), since it hasn't happened again in any further episodes.

There is also a problem with Next Up showing at all, since I have "Play next episode automatically" disabled (from web interface settings). Or does that only affect the web player? There is no similar setting on Android TV app.

This bug happened on Android TV (Firestick 4k max) v0.13.3, server version 10.7.7, player Exoplayer, video was beeing transcoded (burned in PGS subtitles).

### Application version

0.13.3

### Where did you install the app from?

Amazon Appstore

### Device information

Amazon Fire stick 4K MAX

### Android version

Fire OS 7

### Jellyfin server version

10.7.7

**Comment by mueslimak3r** [comment]
Can you test further and confirm whether having next up disabled does fix this?

I've experienced this in the past with both libVLC and exoplayer. With a 10.8 server the issue should be fixed for exoplayer but still present for libVLC. This is assuming the issue is what I think it is: the transcode is deleted prematurely, which causes the client to think the video has finished.

If disabling next up does resolve this for you, even with the episodes you experienced it with, then it may be a bug with the code related to next up.

**Comment by InanZen** [comment]
It seems the bug isn't accurately reproducible - starting playback around the point of occurrence doesn't reproduce it.
I've had it happen again with Next Up settings back to default, but also couldn't reproduce it afterwards.
Than once with "Show next video info: Never" the playback just skipped to the next episode without showing any confirmation (only happened once in ~9 episodes, while with the default settings I've encountered the bug at about 3/7 episodes).
I haven't remembered to note the time of occurrence to check the log files. There isn't any error in the logs but a lot of warnings (Slow HTTP Response).

**Comment by mueslimak3r** [comment]
Please upload server logs and the relevant ffmpeg log when you next experience the issue. I don't expect there to be an error in the server log. What I will be looking for is ffmpeg exiting prior to the client stopping playback. This would  confirm that the issue is related to the transcode file prematurely being deleted.

If this isn't occuring, then we can look elsewhere for a cause

**Comment by Kille250** [comment]
Same is happening on my intance. Only on LibVLC
