### ISSUE TITLE
Disabling "DTS bitstream" option wont trigger audio transcode

### ISSUE THREAD

**Issue by Andy2244** [jellyfin/jellyfin-androidtv#1698]
### Describe the bug

I would expect that leaving the "DTS bitstream" playback option disabled, while having "Direct" playmode enabled, should always trigger a audio transcode on the server, for DTS only files or if set as default track.
Yet the server still sends the DTS files as direct play?

### Application version

0.13.4

### Where did you install the app from?

Sideloaded APK

### Device information

Shield 2019

### Android version

Android 11

### Jellyfin server version

10.8-unstable

**Comment by branches78** [comment]
Turning ON the option should passthrough the codec directly as long as the device you're using has support otherwise the codec should transcode to Dolby Digital.

Turning OFF the option should decode any DTS codec as PCM.

There is also necessary to have a Dolby TrueHD option that does exactly the same.

Currently the DTS option is not working very well depending on the device and it's something I explain in detail in my post:

https://github.com/jellyfin/jellyfin-androidtv/issues/1753
