### ISSUE TITLE
no OptionsItemEditText class?

### ISSUE THREAD

**Issue by Andy2244** [jellyfin/jellyfin-androidtv#1771]
Hi, i cant find any options class that is a simple user editable textbox?

I want to add some options for smb username/password handling.

Any hints?

**Comment by nielsvanvelzen** [comment]
We try our best to never ask for text input on a TV device. That's why we don't have any preference UI for it either.

**Comment by Andy2244** [comment]
@nielsvanvelzen mhh guess this was removed than at some point, since i have old code that creates a "EditTextPreference"

I try to get/set the smb user/password, since "guest" access on windows is kinda broken.
The only other workaround i can think of, is to encode the user/pw directly into the "directpath" uri on the server settings?

Any better ideas?

**Comment by nielsvanvelzen** [comment]
The preference code was rewritten in 0.11 and now wraps the default preference UI from Android. There is no wrapper for the EditTextPreference so that's why it's not here now.

All of the possible options are in this package:

https://github.com/jellyfin/jellyfin-androidtv/tree/master/app/src/main/java/org/jellyfin/androidtv/ui/preference/dsl

**Comment by Andy2244** [comment]
ok thanks, guess i will try the URI encode method, not feeling like writing my own class.
