### ISSUE TITLE
Remember Aspect ratio (like Playback speed)

### ISSUE THREAD

**Issue by xtrandom** [jellyfin/jellyfin-androidtv#1981]
### Describe the feature you'd like

First of all, thanks to all the contributors who are continuously improving the client!

Just like how Playback speed is remembered (until the app is restarted or manually changed), the app should similarly remember the aspect ratio changes. I believe the aspect ratio feature is currently only available when using ExoPlayer.

An alternative, probably requiring more effort, would be to add an option in Settings (perhaps in Playback > Video section) to set the default aspect ratio and use that. Until more media players are support, this could be visible when ExoPlayer is selected.

**Comment by RTUnit** [comment]
I would also like to have this feature (in ExoPlayer).

I have old CRT TV which is 4:3 aspect and all my videos are 16:9. Although it is requiring only a few clicks on remote (ok, down, down, right, right, right, ok, down, ok) per each movie, still would be nice addition to avoid this clicking.

Especially would come handy for TV shows because aspect is reset for every next episode.

**Comment by Darkhost1999** [comment]
Auto crop doesn't do what I desire it to. Most movies end up having the video crop off the screen on top and bottom with Auto crop Enabled.
Remembering and even allowing aspect ratio to be set to a value of 16:9 would work perfectly and the TV web ui already allows setting aspect ratio to 16:9 I didn't check for remembering.
Some movies require both a crop and aspect ratio 16:9 and I don't know why but that's what's needed to return best results imo. For those the Auto crop + the aspect ratio works good enough. But would still be cool to input a manual value for crop and to have any configuration option for aspect ratio at all.
