### ISSUE TITLE
300 ms sound delay on liveTV with LibVLC

### ISSUE THREAD

**Issue by avionics75** [jellyfin/jellyfin-androidtv#2120]
### Describe the bug

Hello !

On all my androidtv devices using jellyfin for androidtv client I can experience a 300 ms sound delay when watching liveTV with the LibVLC player. This delay is not present when using Exoplayer.

To solve the issue, I have to add a -300 ms delay manually when watching the stream.

Using LibVLC is better for me as the buffering time when watching LiveTV is shorter.

Thanks again for this great app !

### Application version

0.14.3

### Where did you install the app from?

Google Play

### Device information

Xiamo Mi Stick 4K, Philips Ambilight, TCL TV

### Android version

Android 11, 8, 9

### Jellyfin server version

10.8.5

**Comment by VampiricAlien** [comment]
With the latest updates, live tv now works with android exo player. I've always found llibVLC to have a delay with everything.

**Comment by Harteex** [comment]
I also seem to get a sound delay on everything I play with libVLC. Exoplayer works good.
Using the Nvidia Shield.

**Comment by plicit** [comment]
I also have to delay audio by about -350ms on every video with Jellyfin on Fire TV Stick 4K Max.  I like libVLC since I can dynamically adjust the subtitle and audio delays.

In lieu of finding the cause of the problem, it would be very helpful to have a global audio delay setting for libVLC, so I don't have to tap the delay button 30+ times for every video.  Thank you for this software! :)

**Comment by plicit** [comment]
@VampiricAlien thank you so much!  I don't know how I missed that option 🙂
