### ISSUE TITLE
Playback speed can be selected but has no effect. 

### ISSUE THREAD

**Issue by Media250** [jellyfin/jellyfin-androidtv#2367]
### Describe the bug

Current setup is streaming from PC to TV. When watching shows and movies, the playback speed option is available and can be changed but the setting does not actually affect the speed. When changing the player to libvlc, the playback speed does change, but the audio cuts out at anything other than 1x speed.

Playing on PC has no problems changing speed. 

### Application version

0.15.0

### Where did you install the app from?

Google Play

### Device information

Hi-sense U8H

### Android version

Google TV

### Jellyfin server version

10.8.8

**Comment by FarisR99** [comment]
Experienced the same issue of playback speed having no effect this week streaming from my Ubuntu server to my my Shield Pro.

**Comment by momelod** [comment]
+1 for me too.

**Comment by DavidFair** [comment]
Unfortunately there isn't much we can do...

I ran into this not long after implementing the functionality to control playback speed. I suspect your using exoplayer with your content?

Debugging the exoplayer source code and communicating with the exoplayer devs this appears to be effectively device specific. Under the hood we ask exoplayer (which relays this to the device) we'd like to play at x speed. 

The device then applies some internal heuristic (I suspect) to determine if this is actually something supported given the bitrate, codec... Etc.

Jellyfin then gets a callback from the TV saying we're now playing at this speed. When the internal algorithm determines it can't support the requested speed it effectively just returns 1x, so the button does nothing from a user's POV.

I've semi confirmed this by buying an Nvidia Shield which could play some content at higher speeds my TV wouldn't attempt.

You can try to force transcoding by dropping the bitrate and tweaking the codecs the server will support to tailor it to your TV. You can also try the VLC player instead, but I've noticed this will stutter and fail to keep up if content is demanding, instead of falling back to 1x speed.
Ultimately this is out of our control as far as I can tell. But I'm happy to be corrected and do further investigation if someone has an idea...

**Comment by Kuphi** [comment]
This is still an issue as of 29.08.2024. Would love if this could get fixed. Is an Amazon Fire TV Stick 4k Max 2023 too slow for accelerated 4k playback? (H.265, 10bit, 2880x2160, 2500kbit/s average). Thanks!

**Comment by nylimited** [comment]
> This is still an issue as of 29.08.2024. Would love if this could get fixed. Is an Amazon Fire TV Stick 4k Max 2023 too slow for accelerated 4k playback? (H.265, 10bit, 2880x2160, 2500kbit/s average). Thanks!

I have not had any issues with Firestick 4K Max and full 4K playback (.265, 10 bit etc) when using Plex. Hence my guess would be that it is not a Firestick problem ...

**Comment by Kuphi** [comment]
> Debugging the exoplayer source code and communicating with the exoplayer devs this appears to be effectively device specific. Under the hood we ask exoplayer (which relays this to the device) we'd like to play at x speed.

It seems this is the active repository of exoplayer: https://github.com/androidx/media

I was not able to find the issue regarding playback speed. Can anyone find it? Otherwise we should open one.

**Comment by ahmadmucom** [comment]
I implemented a fix for playback speed control with EAC3/DTS/Dolby Atmos audio codecs. Since I'm not an Android developer, I worked with AI assistance to develop this solution.

### Technical Approach

The issue is that Android TV hardware audio decoders (used for passthrough/offload) don't support playback speed changes for compressed formats like EAC3, DTS, and Dolby Atmos. The solution dynamically switches between two decoder strategies based on playback speed:

1. **At 1.0x speed (normal playback):**
   - Uses platform decoders with audio offload enabled
   - Full Dolby Atmos/TrueHD passthrough works
   - Maximum audio quality preserved

2. **At any other speed (>1.0x or <1.0x):**
   - Recreates the ExoPlayer instance with FFmpeg extension renderer mode preferred
   - Forces software decoding to PCM (uncompressed audio)
   - Playback speed changes work correctly
   - Audio is decoded to PCM (no spatial metadata like Atmos, but lossless decode quality)

### Implementation Details

The fix modifies:
- `app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java` - Legacy playback system
- `playback/media3/exoplayer/src/main/kotlin/ExoPlayerBackend.kt` - New playback system

When speed changes between 1.0x and non-1.0x, the player is recreated with the appropriate renderer configuration. This causes a brief pause (~1-2 seconds) during the transition, which is acceptable for this use case.

### Known Limitations

- Brief pause when switching between 1.0x and other speeds (player recreation)
- Dolby Atmos/spatial audio is lost when speed ≠ 1.0x (decoded to PCM)
- Affects all audio formats, not just EAC3/DTS (for consistency)

### Why This Solution

Playback speed control is essential for my workflow, and I prioritize it over maintaining Atmos during speed changes. I was previously transcoding my library to include AAC tracks, which was time-consuming and reduced quality. This solution provides:
- Full quality (Atmos) at normal speed
- Working speed control when needed
- No need to pre-transcode media files

### Future Maintenance

I plan to maintain this as a soft fork, rebasing every few months to stay current with upstream changes. I'll test after each rebase to ensure compatibility.

### Build Artifact

A debug APK built with this fix is available here:
https://github.com/AhmadMuj/jellyfin-androidtv/actions/runs/19678362131

### Potential Integration

I'm not opening a PR at this time to avoid wasting maintainer time, since this approach has trade-offs. If the team is interested, I could contribute a settings flag to enable/disable this behavior, allowing users to choose between Atmos quality and speed control flexibility.
