### ISSUE TITLE
Nvidia Shield - Exoplayer transcodes subtitles when playing Dolby Vision 

### ISSUE THREAD

**Issue by Nicholas-Hall** [jellyfin/jellyfin-androidtv#2374]
### Describe the bug

1. set exoPlayer as prefered media player
2. play dolby vision file
3. select a subtitle

Result: app will force exoPlayer to burn in subtitles and transcode.

Expectations: using exoPlayer I would expect Direct Stream. I expect this because using just player as an external player will play dolby vision and the subtitles direct stream just fine.

Questions that I have: when a file is played back does the server choose to transcode or does the client choose to transcode?

### Application version

0.15.0

### Where did you install the app from?

Google Play

### Device information

Nvidia Shield Pro

### Android version

Android 11

### Jellyfin server version

10.8.8

**Comment by MSTRKKRFT** [comment]
Same issue here on last ATV client. Even SRT subtitles have troubles playing fine with Dolby Vision MKV... If I choose Kodi19/20 as an external player I can play the file juste fine, with PGS or SRT subtitles. Maybe just updating exoplayer could help ? (because I think Kodi is also using exoplayer, right?)
