### ISSUE TITLE
On seek video get paused

### ISSUE THREAD

**Issue by Anawaz** [jellyfin/jellyfin-androidtv#2399]
### Describe the bug

When I seek few seconds using remote of my device after seeking video get paused. I have to play that again. I think on seek video should keep playing. 

### Application version

0.15.1

### Device information

realme tv stick 

### Android version

android 11

### Jellyfin server version

10.8.1

**Comment by zhangpeihong** [comment]
yes!! After seeking , video should auto play .

**Comment by tim-vk** [comment]
I thought: "yes, this annoys me, lets solve this!".

So I did some digging around. And I think this behavior is determined by the 3rd party library "leanback" managed by google ( [this thing](https://android.googlesource.com/platform/frameworks/support.git/+/a9ac247af2afd4115c3eb6d16c05bc92737d6305/leanback/src/main/java/androidx/leanback) specifically in [PlaybackTransportRowPresenter](https://android.googlesource.com/platform/frameworks/support/+/300475fc42431cefb0d8f1bfc70de1a7a052a501/leanback/src/main/java/android/support/v17/leanback/widget/PlaybackTransportRowPresenter.java).

The play command is only given when you escape the seek bar (either by play, or moving away from it).

Changing this behavior would mean to write a custom implementation for this. 
I am too lazy to do that. But hopefully this info helps if someone wants to pick this up.

**Comment by 0x6d61726b** [comment]
I am facing the same issue and it is very annoying to press a sequence of keys when seeking within a video.
I did some research and I am wondering if https://github.com/android/tv-samples/issues/31 might be a solution?

**Comment by paulolesgaz** [comment]
Same issue.

I guess it's because the buttons backward/forward on the remote, instead of directly do the action on yhe playback of the video, it calls the seekbar and move the cursor on the bar.

Is it possible to change this behaviour ? 
I mean, if the seekbar is not displayed on screen, pushing on backward/forward button should do the action of going foward or backward and continue playing the video, and call to action to display the seekbar (and all other stuff).
