### ISSUE TITLE
Scrubbing Images - Add Support for Jellyscrub

### ISSUE THREAD

**Issue by NeuroDawg** [jellyfin/jellyfin-androidtv#2504]
### Describe the feature you'd like

There is a great Jellyfin plugin that creates a trickplay file for images that appear when scrubbing the timeline. It's called [Jellyscrub](https://github.com/nicknsy/jellyscrub). The Jellyfind Media Player just added support for this plugin (must be enabled in settings), and it would be absolutely fantastic if this could be added to the Android TV client.

Thanks!

**Comment by anthonylavado** [comment]
From the Jellyfin Media Player 1.8.1 [release notes](https://github.com/jellyfin/jellyfin-media-player/releases/tag/v1.8.1):

>Note: Adding support for this is intended to alleviate the alternative which is people manually patching the client. **Please do not bother other Jellyfin client maintainers to add unofficial plugin support.** In the event that official Jellyfin functionality replaces unofficial plugins or renders them unusable, unofficial plugins will be dropped.

It was only done there because it uses a special version of the web interface that is difficult to modify without building it yourself. It is not an easy task to add to other clients, and it is not an official plugin. The interface for it could change at any time.

If and when we implement something like this in the server, then we can look towards implementing it in more clients.

**Comment by NeuroDawg** [comment]
My apologies. Let's hope you include it in the server soon.

**Comment by anthonylavado** [comment]
No worries. We'd like to do something soon!

**Comment by nielsvanvelzen** [comment]
Like @anthonylavado said, we don't support third party plugins in our official apps so I'll close this issue.
