### ISSUE TITLE
Iconsistent seek when using dpad buttons on remote

### ISSUE THREAD

**Issue by d8f6** [jellyfin/jellyfin-androidtv#2529]
### Describe the bug

So, the onscreen buttons to rewind and fast-foward go ten seconds back or thirty seconds forward respectively, but when using the KEYCODE_DPAD_LEFT or KEYCODE_DPAD_RIGHT both go backwards or fowards thirty seconds only. When using fast-forward and rewind buttons on remote, things work as expected.

### Application version

0.15.3

### Where did you install the app from?

Sideloaded APK

### Device information

Nvidia Shield 2015

### Android version

LineageOS for microG [foster]

### Jellyfin server version

10.8.9

**Comment by francislavoie** [comment]
Some of this is mentioned in https://github.com/jellyfin/jellyfin-androidtv/issues/460 as well.

**Comment by francislavoie** [comment]
This is still a problem.

**Comment by glat** [comment]
Same here on Shield Pro 2019 + App for Android TV from Google Play.

**Comment by nielsvanvelzen** [comment]
Should be fixed in the next 0.16 beta

**Comment by 0-MegaMind-0** [comment]
@nielsvanvelzen  i'm on 0.16.1 (updated to the latest version available on google play store). The changelog indicates that this should be fixed in 0.16.0.

But trying this on my TV the timer is still fixed to default 30 seconds. The ui Settings->playback doesn't list any options to change the seek timings either. 
I even tried to change the timings for the same logged in user on web browser and change the playback seek timings there and clear data on Android TV and re login to see if the new timings will be synced but no changes.
