### ISSUE TITLE
Make Titles Bold

### ISSUE THREAD

**Issue by iDoNtCaRe-69** [jellyfin/jellyfin-androidtv#2637]
### Describe the feature you'd like

Please Make **Titles** & **Headings** Look Bolder. Also It'll Be A Great If App Follows System Font Or Atleast An Option To Change Font From **Roboto** To **Google Sans**. I've A Google TV Which Have Comes With Google Sans By Default. Every Other App Follows The Same Font Except Jellyfin. Same Can Be Said For Every Other Officially Supported Jellyfin Clients.

**Comment by DavidFair** [comment]
I'm going to disagree:

> Same Can Be Said For Every Other Officially Supported Jellyfin Clients.

- Jellyfin web uses Noto Sans for a start: https://github.com/jellyfin/jellyfin-web/blob/master/src/styles/noto-sans/index.scss#L5

> Every Other App Follows The Same Font Except Jellyfin

- That's because the Google style guide now recommends Google Sans. However the license isn't open (unlike Roboto) so I doubt it's available for Fire TV / AOSP builds (unless someone bundles it), which is a nice bit of lock-in to the Android system.  (https://developers.google.com/fonts/faq#can_i_use_the_product_sans_or_google_sans_fonts)

> Also It'll Be A Great If App Follows System Font Or Atleast An Option To Change Font From Roboto To Google Sans.

- This is yet another toggle and maintenance burden (such as additional font handling code to switch and check the availability ...etc.)

That being said, consistency would be great, and I'd like to strive to improve the UX wherever we can, but the licensing on the font means it's not an easy win.

**Comment by iDoNtCaRe-69** [comment]
If Tackling Licence Is Too Much. Then Atleast Try Making An Option To Use Some Open Source Fonts That Look Similar To Google Sans. Like Manrope, Open Sans, Libre Sans. There Are Countless Other. Comparing It With Any Modern ATV App, Defined Looks Bad. Not Ugly, But Definitely Below Average. 

Well All Comes Down To Maintainer, I'm Just A Regular Guy Can't Do Much Then Open Issue Tracker.

**Comment by iDoNtCaRe-69** [comment]
Btw Main Point Of This Issue Is To Make Title Bold. Font Stuff Comes Later/Never. Currently Title, Subtitles & Even Tags All Uses The Same Weight. Bold, Black, Mono, Italic, Light-Italic & I Guess Noto Have All Of These. Please Make Jellyfin Look Decent. 

Just Open Any OTT Apps Like Netflix, & Tell Me If Bold Titles Look Neat Or Not. Normally Android TV Have Bigger Screen, So Utilising Every Corner Should Be A Top Priority. To Me Atleast Everything Looks Scaled Instead Of A Better Approach. For Example, Texts Below Play/Resume, Watched, Other Options, Etc Looks Pretty Cool. 

If I Look At Title, It Can Surely Cover A Wide Space. There's Literally Nothing In The Top Except User & Clock.

**Comment by nielsvanvelzen** [comment]
We do want to improve the UI and appreciate feedback on the current/future changes to it. However, opening an issue for small details like the boldness of a title doesn't help us at all. I'd also suggest to not use title casing in your complete message because it's extremely annoying to read and definitely doesn't motivate us to help with an issue.

**Comment by iDoNtCaRe-69** [comment]
Sure I Understand. I'll Stop Making Requests On Small Stuff From Now On. Well Can't Do Anything About That Last Part, It's A Habit Of Mine & I'm Not Ashamed Of It. Let's Respect Each Others Choice.
