### ISSUE TITLE
External player does not work on Google TV 4K

### ISSUE THREAD

**Issue by RTUnit** [jellyfin/jellyfin-androidtv#2687]
### Describe the bug

1. Install any player in Google TV (4K version), for example MX Player or VLC
2. Login to Jellyfin app on Google TV 4K
3. Choose External player under Playback settings
4. Play any movie

Error message displayed: Cannot play this video format

The same problem occurs either server is transcoding or direct streaming.

### Application version

0.15.6

### Where did you install the app from?

Google Play

### Device information

Google TV 4K (Chromecast)

### Android version

Android TV OS version 12

### Jellyfin server version

10.8.9

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [X] External player (VLC, mpv, MX Player)

**Comment by ACR-Jeff** [comment]
I am assuming you're having the same issue I had, Your format is HEVC? If so I have had this exact same issue, It's in the settings on MX Player, In the Local Player Settings > Decoding Select all "HW+ Decoder" settings that you prefer or need, Remove all others, Select your preferred "HW+ Video Codecs" In my case I choose "H.264 and H.265" and removed all others especially with "Hardware Accelerated" tag behind them, Yours may differ depending on your file format.

Hope this helps.

**Comment by Jpkribs** [comment]
@RTUnit I was experiencing the same issue. I have since been able to get this working as it appears as though the issue stems from Google TV giving different default permissions than other iterations of Android TV. To resolve this issue:

1. Go into Settings
2. Go to Apps
3. Go to Jellyfin
4. At the bottom of the page, there is an option for Permissions
5. Enable Jellyfin to "Allow" for "Files and Media"
6. Force Stop Jellyfin or restart your Chromecast for the changes to take effect

I hope this helps!

**Comment by a413107719** [comment]
I have the same issue with high version jellyfin.
But it works fine while  downgraded to v0.12.3.

**Comment by Angell1993** [comment]
I've run into this very same problem, on two identically encoded 4k movies av1 + opus, one plays fine while the other keeps saying, Cannot play this video format.. I use mpv as external player, because It's my favourite player, but the Android version is severely lacking compared to the one on arch linux.. 

I've tried to use mediainfo app on desktop to check the mediainfo but I can't find anything different between the two..

How is this possible??
Jellyfin app jellyfin-androidtv-v0.16.0-beta.5-release.apk, as I was trying to see if the beta version had any fixes for my issues over the Google Play version, but sadly none so far to my knowledge..

**Comment by NooNameR** [comment]
same here for Android TV (Sony) 0.15.12 version of jellyfin

**Comment by Carve** [comment]
Works fine on Android (mobile) but not on Android (Google TV - ONN 4K 2023 model with AV1 support). 

If I cast from mobile to the Google TV then it works if I start from the 0:00 timestamp but if I seek or resume it will not play.
