### ISSUE TITLE
DTS is not decoded to PCM anymore

### ISSUE THREAD

**Issue by branches78** [jellyfin/jellyfin-androidtv#2715]
### Describe the bug

Ever since Android 11 arrived, DTS codecs are no longer decoded as PCM on Android TV or Google TV devices, I imagine it's the same on Android 12.

Videos play without sound, but they used to be decoded to PCM when the TV where the device is connected doesn't support DTS decoding by any of its HDMI ports but only PCM decoding.

Turning OFF the DTS option in settings doesn't do anything either.

It's actually annoying having to go back and forth to settings to turn that option OFF when it should stay ON all the time and do proper decoding to PCM or direct passthrough depending on the sink device.

### Application version

0.15.7

### Device information

Every Android TV device or Google TV device

### Android version

Android 11 or later

### Jellyfin server version

10.8.10

**Comment by branches78** [comment]
Looks like this problem has been fixed in Android 12:

I bought the Onn 2023 device which has Android 12 and a security patch dated march 2023, my other two devices are on Android 11, one with a security patch dated november 2022 and the other device with a security patch dated april 2023, on both, DTS is not decoded to PCM when they are connected to a TV without DTS decoding by HDMI, but, on the Onn device, DTS was decoded to PCM when it's connected to the same TV, so the problem is basically Android 11 and only God knows what the problem is.

This issue is going to be closed.

**Comment by branches78** [comment]
I should have not closed this issue since it was still present on some of my devices even on Android 12, but, the issue seemed to have being fixed in the november 2023 security patch that was recently applied to one of my devices (Homatics Box R 4K Plus), however, it just played in stereo instead of being played in multichannel PCM.

There isn't any transcoding log to provide but I will provide the server log in another moment hoping that it shows any useful information.

**Comment by branches78** [comment]
Audio is still decoded as stereo PCM instead of being decoded as multichannel PCM.

**Comment by branches78** [comment]
Nevermind.

**Comment by Juustomunakas** [comment]
Same problem here, on a different device — Strong LEAP-S3 (Google TV, Amlogic S905Y4) connected to a Samsung Q990C soundbar via eARC. Soundbar has no DTS decoding support at all, only Dolby (AC3/E-AC3, Atmos via DD+ JOC).

DTS/DTS-HD content DirectPlays with no sound. Toggling the DTS option in the app settings on/off doesn't change the outcome either way — same as reported here. Confirmed via the playback stats overlay that the audio decoder is handling DTS correctly at the hardware level, but nothing usable is reaching the receiver.

Also tried external players as a workaround (per #4796): Just Player and VLC both go silent on the same files despite claiming DTS support, while MPV (used via a third-party client, Wholphin) correctly decodes DTS to PCM locally and plays fine. So the underlying hardware/HDMI chain is capable — the issue seems specific to how ExoPlayer-based clients on Android TV/Google TV negotiate or fall back on DTS when the connected receiver can't accept it via passthrough.

For comparison, on my Samsung TV I'm running a sideloaded community build (Jellyfin-10.10.z-GrayFix, compiled 2025-10-06) rather than the official Tizen app, and it handles this correctly out of the box — it has explicit "Enable DTS (DCA)" / "Enable TrueHD" toggles under Video Advanced settings, and with DTS unchecked the server transcodes proactively instead of DirectPlaying a track that fails silently downstream. Not sure whether these toggles exist upstream in the official Tizen client too, but that manual-declaration + server-transcode-fallback approach seems like the more reliable fix than expecting ExoPlayer passthrough/decode-to-PCM to work automatically.

Happy to provide playback stats/logs if useful — this is very reproducible on my end.
