### ISSUE TITLE
Double subtitle in ExoPlayer at v0.11.0

### ISSUE THREAD

**Issue by Mantu120** [jellyfin/jellyfin-androidtv#290]
I just tested v0.11.0 on my Android TV, and found double subtitle issue if ExoPlayer is seleted.
 
![subtitle_issue](https://user-images.githubusercontent.com/59708776/73802150-e946c180-47e6-11ea-8ce3-658780eabfa5.png)

**Comment by nielsvanvelzen** [comment]
What kind of subtitles did you use?

**Comment by Mantu120** [comment]
> What kind of subtitles did you use?

Normal SRT subtitle in MKV video file

**Comment by AndreasGB** [comment]
So, I looked into this a bit and I think this could *maybe* be fixed by implementing a custom [TrackSelector](https://exoplayer.dev/track-selection.html) which filters out the subtitle / text tracks, which should prevent exoplayer from rendering them. Won't look further into this today though because sleep.

**Comment by nielsvanvelzen** [comment]
Did some digging into this issue and here is what I found:
- This issue only happens with containers
- It's related to #303

For my example my "test file" will be an MKV file with SRT subtitles embedded as default.
When playing this video with subtitles disabled and no transcoding the server will just send the mkv file. Because the SRT is found by ExoPlayer as a default track ExoPlayer will show it.

When changing the subtitle track, because it's a simple SRT file, the app will download the SRT and display it in it's own subtitle view. But because ExoPlayer still receives the default track... it will display it.
