### ISSUE TITLE
Improve detection for HDR media

### ISSUE THREAD

**Issue by VampiricAlien** [jellyfin/jellyfin-androidtv#2933]
### Describe the bug

No detection for HDR media, not sure about DoVI.
@mohd-akram opened pull request that added support https://github.com/jellyfin/jellyfin-androidtv/pull/2893

Video details from jellyfin web

Video
Title: 4K HDR - HEVC
Codec: HEVC
Profile: Main 10
Level: 150
Resolution: 3840x1744
Aspect ratio: 3837:1744
Interlaced: No
Framerate: 23.976025
Bitrate: 14271 kbps
Bit depth: 10 bit
Video range: HDR
Video range type: HDR10
Colour space: bt2020nc
Colour transfer: smpte2084
Colour primaries: bt2020
Pixel format: yuv420p10le
Ref frames: 1

What about using the below to detect HDR?
Colour space: bt2020nc
Colour transfer: smpte2084
Colour primaries: bt2020

### Application version

0.16.0-beta.1

### Where did you install the app from?

Sideloaded APK

### Device information

SHIELD

### Android version

11

### Jellyfin server version

10.8.10

**Comment by mohd-akram** [comment]
The issue is that on the first load, the app uses the old `apiclient` API which is missing the fields for HDR and Dolby Vision. However, if you minimize the app and open again while a video is highlighted, it does a refresh and you will see those fields, because it use the new SDK for the refresh. I looked into migrating the code responsible for this to the new SDK, but noticed that it uses immutable data classes, and in the case of the first search, it's a very large data class, while the current code gradually populates the search query across different code paths. Out of curiosity, I found a [data class builder](https://github.com/blipinsk/data-class-builder) which perhaps can be added to the SDK for very large data classes to maintain immutability while allowing flexibility. Alternatively, the old `apiclient` package could be updated to support some of the new fields - that might be the simplest solution. @nielsvanvelzen may have some other ideas as well.

**Comment by nielsvanvelzen** [comment]
So I think the best solution is to migrate the API calls to the SDK then. Which I didn't do yet because that code is _a bit_ messy and it might introduce some issues. So unlikely to end up in 0.16.

> Out of curiosity, I found a [data class builder](https://github.com/blipinsk/data-class-builder) which perhaps can be added to the SDK for very large data classes to maintain immutability while allowing flexibility.

The SDK intentionally uses immutable data classes. If you need to modify them you'll need to use the .copy() function, which unfortunately doesn't work nice in Java code hence the ...Helper.kt files you see a bunch.

> Alternatively, the old apiclient package could be updated to support some of the new fields - that might be the simplest solution.

The old apiclient is EOL so it won't get updates. It's been replaced with the Kotlin SDK.

**Comment by DemirG** [comment]
Just wanted to note that I also had problem with JF detecting HDR.

**Comment by guiweber** [comment]
This seems to be the same as https://github.com/jellyfin/jellyfin-androidtv/issues/1177

**Comment by guiweber** [comment]
@nielsvanvelzen As a stopgap measure, we could parse `stream.displayTitle` and extract any HDR indicator. Not sure how reliable it is, but from media in my library HDR streams area always identified (although specific HDR types are not necessarily specified) . I've implemented it as a fallback to the existing (but non-functional) methods and it works well in the emulator.

Let me know if you think that can be a good temporary measure and I'll submit a pull request.

**Comment by guiweber** [comment]
I think `stream.displayTitle` is generated by the server and not raw metadata from the files. It's what Jellyfin Web uses as source for the Video info for movies/shows, so I would assume it to be reliable (even though it would need to be parsed in this case).

**Comment by nielsvanvelzen** [comment]
When `VideoRange` is set to `HDR` in the media stream the item is HDR. That is the only property we'll check. We're not going to parse a title.

**Comment by guiweber** [comment]
This is still an issue...

**Comment by nielsvanvelzen** [comment]
Can you share a screenshot of that behavior and open a separate issue for it?

**Comment by Hello-World-Traveler** [comment]
@nielsvanvelzen  Is there an option for Dolby Vision and HDR together if media has fallback? [DoVI/HDR]

`Video range typeDOVIWithHDR10`
