### ISSUE TITLE
Playback stuttering

### ISSUE THREAD

**Issue by pquerner** [jellyfin/jellyfin-androidtv#2941]
### Describe the bug

1. Install beta 0.16.0-beta1, but this also happened on the previous release version 0.15.11 (however I only have logs from 0.16.0-beta1)
2. Play back a video (cannot determine if resolution or other metadata matters)
3. Playback pauses randomly, not sure if app related or jellyfin-server related (can you spot it in the logs?)

### Logs

I only have logs from a users point, as I do not have permission from the server. Hopefully it shows something nonetheless.

[logs.jellyfinbeta.redacted.txt](https://github.com/jellyfin/jellyfin-androidtv/files/12248113/logs.jellyfinbeta.redacted.txt)

### Application version

0.16.0-beta1

### Where did you install the app from?

Sideloaded APK

### Device information

Nvidia Shield Pro 2022

### Android version

Android 9

### Jellyfin server version

10.8.0 - but unsure

**Comment by nielsvanvelzen** [comment]
Playback is quite complex and this issue can be caused by a lot of factors. You didn't use our playback issue template so a lot of detail is missing. Besides, for troubleshooting we generally recommend using our [contact options](https://jellyfin.org/contact) like Matrix/Forum/Discord as more people are helping out with those kinds of questions there. If you end up finding a bug I'm happy to help further.

**Comment by pquerner** [comment]
I didnt use the template since I dont have access to the servers logs. I think the server is acting up aswell, but maybe something would be found in the clients logs, but I guess not.
