### ISSUE TITLE
[0.16.0-beta.2] Bug in screen saver

### ISSUE THREAD

**Issue by VampiricAlien** [jellyfin/jellyfin-androidtv#2981]
### Describe the bug

If the in app screen saver is turned off,  somehow it also turns off android screen saver therefore TV doesn't turn off by it's self like it once did.

With the in app screensaver, can we teak the logo?  move the logo to the corner ever few minutes (little like the old DVD logo) and take out "jellyfin" but keep the logo shape?

### Application version

0.16.0-beta.2

### Where did you install the app from?

None

### Device information

SHIELD

### Android version

11

### Jellyfin server version

10.8.10

**Comment by nielsvanvelzen** [comment]
Toggling the in-app screensaver might require an app restart to become effective.

**Comment by nielsvanvelzen** [comment]
I've tried debugging this issue and I'm thinking this might be a platform bug. For me the screensaver is not working in any app no matter what settings I use. Maybe this was broken in a Google Play Services update or something similar? When I initially made the in-app screensaver I did test the behavior with it disabled and everything worked at the time.

**Comment by nielsvanvelzen** [comment]
No, it does not. The only thing the in-app screensaver does is tell the system to keep the screen on (which indirectly disables the default screensaver). This will not happen when you disable the in-app screensaver. I don't believe this issue is caused by the app because there is literally no code-path that should be able to introduce this behavior.
