### ISSUE TITLE
Show extras that are part of Seasons folder

### ISSUE THREAD

**Issue by ghost** [jellyfin/jellyfin-androidtv#3009]
### Describe the feature you'd like

According to Jellyfin documentation, extras can either be placed in Season 0, or in subfolders in each associated Seasons.
For example
Season 1 > Extras > extra.mp4
Season 2 > Behind the scenes > bts.mp4

Those are showing on the web and desktop clients. Not in the android tv one.
I'm not sure if this is a bug or feature request.

**Comment by HijackHornet** [comment]
Alright.
Maybe in the meantime extras could be put inside the main row ?
As a workaround I use the mobile app to cast to the TV app the extra it should play.

**Comment by Informationator** [comment]
Just to add to the above, there are two scenarios that would be included in a future UI update, ideally:
1) **Season Level** (as mentioned above)
e.g.  ...\Series (2010)\Season 01\extras\files.mkv
2) **Show Level**
e.g ...\Series (2010)\extras\files.mkv

Maybe there is already an issue for #2, but I just didn't want it getting lost in the mix.  Feel free to delete this if it's redundant. 
  Thank you!

**Comment by nielsvanvelzen** [comment]
It turned out to be possible without too much changes so we will show extras/specials for seasons in version 0.17!

**Comment by Informationator** [comment]
> It turned out to be possible without too much changes so we will show extras/specials for seasons in version 0.17!

This is great news!  I've been looking forward to this feature for a long time.  Could the same logic be used for the show-level as well, or is only the season-level easier to implement?

**Comment by nielsvanvelzen** [comment]
Extras at the show level are already shown as a season 0

**Comment by Informationator** [comment]
Hey Niels, I probably should've been more specific earlier.  I just don't want a supported feature to fall through the cracks:

There is a feature in the documentation which works on the web version where you can have an extras folder at the show level.  That way, instead of extras showing as  one of the "seasons" (which is not really ideal in my opinion), they will show under a "special features" banner as they do with movie extras, and with season-level extras.  Could support for an extras folder be added at for the show level as well in v0.17?

If you look at the file structure under "Show Extras" here you will see what I mean: https://jellyfin.org/docs/general/server/media/shows/

If an extras folder at the show level isn't being added, then this request would not really be complete as of v0.17: https://features.jellyfin.org/posts/1939/display-extras-folders-for-shows-in-androidtv-client-issue-present-in-v0-15-2

I'm happy to give any examples or screenshots if that helps.  Thanks for all of your efforts!

**Comment by nielsvanvelzen** [comment]
Thanks for clarifying, our API only knows "specials" and from what I thought specials on a series are always placed in a season 0. Apparently the server also creates a different kind of specials for series.. I'll see what I can do, can you open a new GitHub issue specifically for that? (this one was for seasons).

**Comment by Informationator** [comment]
> Thanks for clarifying, our API only knows "specials" and from what I thought specials on a series are always placed in a season 0. Apparently the server also creates a different kind of specials for series.. ~I'll see what I can do, can you open a new GitHub issue specifically for that? (this one was for seasons).~ edit: consider it done

You're the best!
