### ISSUE TITLE
longer timeout at connection

### ISSUE THREAD

**Issue by bibitocarlos** [jellyfin/jellyfin-androidtv#3130]
### Describe the feature you'd like

Hi,
Would it be possible to add à few more secondes before to time out at connection, my server needs à little more time to wake up and i couldnt find à way in the source code to modify it ?

Thanks for your work !

**Comment by nielsvanvelzen** [comment]
Can you give some more detail for the use-case? A timeout of 30 seconds is plenty in my opinion, the average user doesn't even want to wait 2 seconds.

**Comment by bibitocarlos** [comment]
I put with à script my server on sleep (ram) when it detects inactivity.
My jellyfin server is behind à caddy server on a pi.
On the caddy server i use wakeonlan plugin to wake up my jellyfin server on every connection on it through https.
The server takes around 7-8 secondes to wake up ( cant verify thé exact timing im not at home)
The jellyfin android gives me à time out error connection on first attempt.
I will test with jellyfin-Web if the timeout is thé samedi.

**Comment by zehnerGIT** [comment]
The timeout value of 30sec seems to work on my Android TV 11 box. My nas spins down all hdds after 15mins of inactivity. My hdds need more than 10sec to wake up. Kodi limited the timeout in the last version to 10sec, so I have to start almost every playback 2 times with the Kodi-client. But on the current Jellyfin androidtv-client, everything works as expected, after about 15sec the playback starts and no exception.

**Comment by nielsvanvelzen** [comment]
Jellyfin does not support Wake on Lan and the app assumes the server is up and running. We use a 30 second timeout in all code using our new SDK. Some parts of the app may still use a faster timeout because it uses our old Java apiclient which is slowly being phased out.
I don't see a point in increasing the timeout. If the app crashes or somehow shows weird behavior we can always work on improving that but that does not appear to be the case here.

Closing as wontfix.

> My point is with jellyfin-android (and maybe jellyfin-androidtv)

You're reporting an issue in the Android TV repository, not the mobile one.
