### ISSUE TITLE
Trailer button disappeared

### ISSUE THREAD

**Issue by andpalmier** [jellyfin/jellyfin-androidtv#3131]
### Describe the bug

Hey everyone,

I've been having an issue with the trailer button on the Android TV version of Jellyfin. It used to work perfectly on TV shows and movies until about 2/3 months ago, but now the button has randomly disappeared. Interestingly, the button is still visible on the web client.
Has anyone else encountered a similar problem? Any advice or suggestions would be greatly appreciated.

Thank you in advance for your help!

### Application version

0.15.12

### Where did you install the app from?

Google Play

### Device information

Strong LEAP-S1

### Android version

Android 10

### Jellyfin server version

10.8.11

**Comment by nielsvanvelzen** [comment]
What type of trailers don't show up any more? Are they local, YouTube or something else? And if they are YouTube trailers: do you have the YouTube app installed?

**Comment by andpalmier** [comment]
I am referring to Tv shows and Movie trailers from YouTube, so not local files. Yes, YouTube application is installed

**Comment by nielsvanvelzen** [comment]
The trailer button will show up if any of these conditions succeed:
1) There is one or multiple local trailers (files on the Jellyfin server)
2) There is one or multiple YouTube trailers and the system can open YouTube links

It appears that the second condition isn't behaving correctly in your case. This may happen because some other app is claiming to open YouTube links but doesn't allow apps to do that. Unfortunately there is no easy way to debug why this issue is happening on Android TV.

**Comment by andpalmier** [comment]
Thanks for your answer. I performed a factory reset on my TV box and re-install Jellyfin and YouTube. Unfortunately, the trailer button is still not there. I am still able to view YouTube videos in the appropriate app without issues and the trailer button is visible in the Android app as well as in the web client.

**Comment by nielsvanvelzen** [comment]
Huh weird, I've also tested it on my own devices and trailers do still work. Unfortunately I don't have any other ideas to try.

**Comment by NetSamurai** [comment]
Mine are gone too.

**Comment by andpalmier** [comment]
@NetSamurai I use default launcher and default Android

**Comment by nielsvanvelzen** [comment]
It could be possible the external trailer URL is not formatted correctly. A YouTube trailer must match exactly `https://www.youtube.com/watch?v=[11 characters here]`. To confirm please use the web user interface for Jellyfin and do the following:

1. Open the browsers developer tools in the network tab
2. Open an item that contains a working YouTube trailer in the browser (but not in the app)
3. Filter the network logs to `/Items/`
4. Click on the network request that has the same id as the item (check with the URL in the browser  tab)
5. Copy the "response" information, it should look somewhat like this:
```
{
	"Name": "Big Buck Bunny",
	"OriginalTitle": "Big Buck Bunny",
	"ServerId": "a3dbcac297814caea766c3aef006ff60",
	"Id": "cf32a08042eac8e3366f9f9ae6a5686d",
	"Etag": "4c6343fe434a2fb2d4deab50de3a562b",
	"DateCreated": "2021-11-16T16:23:55.9788723Z",
	"CanDelete": false,
	"CanDownload": true,
....
```

Search for the part that contains "RemoteTrailers" and post it here, it should look somewhat like this:
```
	"RemoteTrailers": [
		{
			"Url": "https://www.youtube.com/watch?v=aqz-KE-bpKQ",
			"Name": "Big Buck Bunny - Official Blender Foundation Short Film"
		}
	],
```

**Comment by NetSamurai** [comment]
For what it's worth, I have the `RemoteTrailers` object in my JSON, however its an array with just [{Url: "https://www.youtube.com/watch?v=validURL" }] ; the `Name` attribute is missing.

**Comment by nielsvanvelzen** [comment]
The name attribute is ignored by the app so that doesn't matter. The URL also seems correct so that can't be the problem either.

**Comment by andpalmier** [comment]
I can also see the `RemoteTrailers` object without issues

**Comment by abemedia** [comment]
I have the same issue on my Chromecast with Google TV. Trailers work on Android mobile app and web interface, but the button is not displayed on Android TV.

**Comment by nielsvanvelzen** [comment]
The issue might be fixed with #3265. You can test it out (or wait for 0.16.3 which will include it).

To test:
- Go to the build artifacts (https://github.com/jellyfin/jellyfin-androidtv/actions/runs/7350068182)
- Scroll down and click on the "build-artifacts" link in the "Artifacts" section
- Unzip the file
- Sideload the .apk file to your device

It will install as separate app (Called Jellyfin Debug, with an orange logo)

**Comment by andpalmier** [comment]
Apologies @nielsvanvelzen for commenting again on this one, but I am still having this issue.

Jellyfin app version: 0.16.5
Android version: Android TV OS 12
Jellyfin server version: 10.8.13

YouTube app works perfectly, and the trailer button is visible in the Android non-TV app as well as in the web client.

**Comment by mo-st** [comment]
Had the same problem and managed to fix it so I thought I'd share. I _thought_ I had the youtube app installed as well, alongside SmartTube. Turns out upon closer inspection, this was just a SmartTube ATV bridge app, uninstalling youtube in the TVs play store (with note: This app wasn't installed by Google) and then reinstalling it returned the trailer button.
