### ISSUE TITLE
"Play with" does not support resuming of previous playback position

### ISSUE THREAD

**Issue by spoolr** [jellyfin/jellyfin-androidtv#3180]
### Describe the bug

With the latest FireTV version in the Amazon Store on a FireTV 4K:

Change "Preferences"->"Playback"->"Preferred media player" to "Always Ask"
Pick something from "Continue Watching" and select it
Choose "Play with" and selecting any of the choices offered (LibVLC, ExoPlayer etc) will playback from 0:00

(Why do I have Always Ask?  It's because I watch Movies with Atmos with the External Player (Kodi) but stick with ExoPlayer for TV stuff in Jellyfin)

### Application version

Latest version in Amazon Store

### Device information

FireTV 4K

### Android version

Latest version in Amazon Store

### Jellyfin server version

10.8.12

**Comment by nielsvanvelzen** [comment]
Does this only happen when using the "Always ask" option or also when always using an external player?

**Comment by spoolr** [comment]
This is just a problem with "Always Ask".  If I set it to ExoPlayer always, then I see the "Resume at xxx" button in additional to a generic "Play" button.  So it seems the "Play" button becomes the "Play With" button, and the "Resume at xxx" button just goes away.  I wasn't aware that there would be two buttons when a media player is set.  Still, It would be beneficial if a Resume option was made available.

If I set it to External App, the "Resume" button and "Play" button show up, but "Resume" does not resume.    For the external app, I don't personally need this functionality.  TV shows are postpone able, but movies I treat like the movie theater.

**Comment by nielsvanvelzen** [comment]
It appears that we don't show the "resume" button because there is no code to show the menu to select a player for it.

**Comment by luxzg** [comment]
+1 to same issue with Android TV app on Play Store as well.

Considering that different players behave differently, this issue is annoying enough that my current workaround is to have internal player set as default, and when certain videos refuse to play then I go to app settings and enable external player, then switch back after playback is finished. But that's not something rest of the family is willing or able to do.

LibVLC and Exo don't know how to play some formats (eg DVD ISO), VLC doesn't report playback pause/resume (separate issue : https://github.com/jellyfin/jellyfin-androidtv/issues/1208 ), Just Player resomes but has issues with some videos, and so on. So there's hard to find one player to keep as THE default. And using "Play with" would be good enough, and easy to explain to other family members, but broken pause/resume even for players that do support playback reporting makes it another no-go.

Also, maybe reopen that VLC issue that is closed as stale but not resolved.

**Comment by nielsvanvelzen** [comment]
Closing as the "play with" feature is no longer available.
