### ISSUE TITLE
Option to exclude libraries from screensaver

### ISSUE THREAD

**Issue by sjiawjbssj** [jellyfin/jellyfin-androidtv#3320]
### Describe the feature you'd like

It would be great if I could choose which libraries are being used for the screensaver images.

**Comment by Wortex17** [comment]
Yes, especially since age rating doesn't seem to be incorporated at all either

**Comment by nielsvanvelzen** [comment]
It is not currently possible to filter out libraries when requesting random items from the server. This means it won't be possible to filter out specific libraries without making **a lot** of requests to the server, which is not ideal.

From the feedback I gathered in various places most users want to filter out specific libraries because it contains content not suitable for children (or family). So my suggestion is to filter items with an age rating of PG-13 or less (note that no age rating will also show). This is easy to implement and will fix the underlying problem for most users.

Additionally, we could make this age-rating filter optional (but enabled by default). I'll probably implement it without a preference first so we can backport it to the current 0.16 release.

**Comment by nielsvanvelzen** [comment]
> Would it be possible to make it customizable which age ratings to exclude? I just want to remove XXX and no rating content.

Yes, what is going to happen is:

- Starting with 0.16.5 (next release) the screensaver will only show PG-13 rated items and everything without a rating
- Starting with 0.17.0 the screensaver will only show PG-13 rated items (without unrated items) by default. But both options will be configurable

**Comment by ironicbadger** [comment]
Excluding certain libraries would be my suggestion.
