### ISSUE TITLE
Jellyfin for Android cannot connect to server [but web browser can connect!]

### ISSUE THREAD

**Issue by plasmatic-prime** [jellyfin/jellyfin-androidtv#3383]
### Describe the bug

1. Jellyfin installed & running via docker on our server
2. jellyfin.[mydomain].com loads up Jellyfin and permits users to log-in via web browser; content can be browsed and watched
3. Jellyfin client for Android [official client installed from Play Store] cannot connect to the server at jellyfin.[mydomain].com; tries both http and https and both standard ports

### Application version

0.16.5

### Where did you install the app from?

Google Play

### Device information

Nvidia Shield Pro 2019

### Android version

Shield Android TV 9.1.1 (33.2.0.157)

### Jellyfin server version

10.8.13

**Comment by plasmatic-prime** [comment]
@VampiricAlien :: yes, we tried the IP address as well, shortly after posting the bug. Same result. Jellyfin for Android cannot connect to the server. Our SSL certificate is issued by Let's Encrypt. The SSL settings in Jellyfin are not set to force https connections, but the web browser does report a secure connection, so all seems well there. Really confused on this one.

**Comment by nylimited** [comment]
Is this somehow a new issue?   I installed the client app from Amazon appstore on a Firestick. Worked fine yesterday and a few days before.  Both, my TV and the server are on the same LAN so I simply pointed it to the local IP of the server.  Like I said, it all worked till today.

Somehow it can longer find the local IP and port but all my other devices on the same LAN can ...  thoroughly confused ...  :-(

**Comment by dglava** [comment]
I started experiencing the same error issue recently. On the server connection page, it says "SSL-Handshake failed". I am using a certificate signed by LetsEncrypt and it used to work without issues. There have been no updates to Jellyfin-AndroidTV as far as I can remember since the last time it worked for me (a few days ago, but not completely sure). I have tested it via a web-browser and it's working.

I have seen other issues mentioning that TLS1.3 might not be working with certain older hardware, so I disabled it on my server. The error persisted.

Are there any logs I can check to get to the bottom of this? My Jellyfin server logs don't mention anything about this.

**Comment by zeaglee** [comment]
I have the same issue with jellyfin android tv 0.16.5 and the unstable docker image. Says session is authenticated in jellyfin log.

**Comment by thornbill** [comment]
Unstable is not supported by the app

**Comment by zeaglee** [comment]
> Unstable is not supported by the app

Ok thanks. That's too bad but I'll wait for 10.9 proper to come out. It solves a tone mapping issue for my other devices that is present on 10.8.

**Comment by nielsvanvelzen** [comment]
If you could share logs of the app I can see if it is an easily fixable bug but it is as @thornbill says; we do not support unstable versions of the server in our apps. Make sure to update your unstable build first as we've already made some fixed for backward compatibility 1-2 weeks ago.

**Comment by nielsvanvelzen** [comment]
We do not support unstable. Remove all your data and install 10.8.13.

**Comment by MaxiHafer** [comment]
I understand you do not support unstable, but maybe reviving https://github.com/jellyfin/jellyfin-androidtv/pull/3309 to inform users about this decision would be feasible? I didn't mean to bother you.

**Comment by kevgrig** [comment]
I hit this same issue on unable to login when using the jellyfin server `master` branch but building the server on `release-10.8.z` with .NET 8.0 hit lots of errors so I had to do the following (on Fedora) and then I could log in:

```
git checkout release-10.8.z
sudo dnf install dotnet-sdk-6.0
dotnet new globaljson --sdk-version $(dotnet --list-sdks | awk '/^6/ {print $1}')
dotnet clean
dotnet build
```

**Comment by SamMousa** [comment]
I think the issue is the same for the findroid client. The server (in 10.9) requires some extra attributes as part of the login message / communication..

**Comment by nielsvanvelzen** [comment]
I'll be closing this issue now because it is tiresome to keep repeating myself. We do not support unstable builds in our official Android apps.

**Comment by SamMousa** [comment]
How about instead labelling it as @ blocker for 10.9 stable release? Since you can't do a stable release if the apps don't work on it yet? 😕

**Comment by nielsvanvelzen** [comment]
You can find everything there is to know about 10.9 in this issue: https://github.com/jellyfin/jellyfin-androidtv/issues/3467. The login issue is already solved and will be in the next unstable release.

**Comment by jorensanbar** [comment]
Hello! @nielsvanvelzen . I got this error.

Server: Jellyfin Server 10.9.10
Android App Jellyfin 2.6.2 (Play Store)

I can connect by web.
I can detect server in list (web and app)

but when i select the server the 5 connection attempts keep failing

**Comment by lhoosconciso** [comment]
I'm having this issue on `10.10.5`. The server runs in docker container in my home LAN. I have no issues connecting via a web browser, but my Google TV fails with an error message similar to the screenshot a few posts up. The weird thing is that it works _sometimes_, but I haven't figured out a pattern. The server is always auto-discovered, but I can't connect. Connecting to `demo.jellyfin.org/stable` always works.

After trying a few things, I was eventually successful by typing in the IP address instead of the hostname. Could it be that my Google TV sends its DNS queries straight to some DNS server on the internet instead of my router? I wasn't able to find any DNS configuration in the Google TV settings.

**Comment by Rapti** [comment]
**Edit:** It later turned out I unknowingly had a second DNS server running in my local network. I turned it off and after that it worked.

I'm having this issue on `10.10.5`. The server runs in docker container in my home LAN. I have no issues connecting via a web browser, but my Google TV fails with an error message similar to the screenshot a few posts up. The weird thing is that it works _sometimes_, but I haven't figured out a pattern. The server is always auto-discovered, but I can't connect. Connecting to `demo.jellyfin.org/stable` always works.

After trying a few things, I was eventually successful by typing in the IP address instead of the hostname. Could it be that my Google TV sends its DNS queries straight to some DNS server on the internet instead of my router? I wasn't able to find any DNS configuration in the Google TV settings.

The same happens on the two android phones I've tried this on. IP address works, hostname doesn't.

**Comment by anatoly314** [comment]
Have the same issue. Jellyfin runs in k3s in home network and ingress that forward jellyfin.example.com with valid Let's encrypt certificate to port 8096. In browser and android phone it works, in tv box it doesn't. When I exposed 8096 via nodeport to 30896 and connected using ip address it worked.

**Comment by rob-h-w** [comment]
Looks like a duplicate of https://github.com/jellyfin/jellyfin-android/issues/1402. I was seeing the same issue. I debugged into the Android service, and it's doing DNS just fine. It couldn't verify the chain because I wasn't using the fullchain cert in my nginx reverse proxy.

**Comment by raulpetru** [comment]
Any idea how we can use fullchain cert using Caddy reverse proxy?

An Android TV box worked like a charm on the same wifi with the server (using the domain not IP), but moving the same Android TV box (after factory reset) in other city it just doesn't work. Keeps getting "Server not found" error.

It worked to connect to the demo server but after still didn't connect to mine. If I made a hotspot from my phone and connected the TV to it, I could connect to my server. After turning hotspot off and connecting back to house wifi, it still connects to the server. Weird.

**Comment by vincent6634** [comment]
Hello everyone,
The problem seems to persist. I tested it with the browser: it works! With other applications, it doesn't work except for Jellyflix, which connects but has bugs. I tested it with another Android TV box: it works, but nothing works with mine. I have a MIBOX 3 with Android 9. 
My SSL connection seems to be compatible with Android 9 when I check on https://www.ssllabs.com/ssltest
Here are the logs I collected with adb: 

`07-25 14:02:50.588  6730  6774 D org.jellyfin.sdk.discovery.RecommendedServerDiscovery: Caused by: avax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xd1d60448: Failure in SSL library, usually a protocol error
07-25 14:02:50.588  6730  6774 D org.jellyfin.sdk.discovery.RecommendedServerDiscovery: error:1000042e:SSL routines:OPENSSL_internal: TLSV1_ALERT_PROTOCOL_VERSION (external/boringssl/src/ssl/tls_record.cc:592 0xd0320ac8:0x00000001)
07-25 14:02:50.588  6730  6774 D org.jellyfin.sdk.discovery.RecommendedServerDiscovery: 	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
07-25 14:02:50.588  6730  6774 D org.jellyfin.sdk.discovery.RecommendedServerDiscovery: 	at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:375)
07-25 14:02:50.588  6730  6774 D org.jellyfin.sdk.discovery.RecommendedServerDiscovery: 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:224)`

version App : Jellyfin-androidtv 0.18.11 release

Thank you all

**Comment by vincent6634** [comment]
Hello everyone,
I think I've found the source of the connection problem, but I don't understand everything.
The connection system is implemented by **OkHttp**. It seems that OkHttp is not compatible with TLS 1.3 on Android 9 and earlier versions.
The **org.conscrypt:conscrypt-android** dependency would need to be added.
[Link](https://stackoverflow.com/questions/55539513/how-to-enable-tlsv1-3-for-okhttp-3-12-x-on-android-8-9)
I don't know how to code, so I can't suggest a change.

Maybe I should make a post for an improvement?

In the meantime, I launch the browser on the server address, connect quickly, and then cast from my phone. It seems faster than Kodi with the add-on.

**Comment by f-liva** [comment]
For me none of these solutions worked except switching to an alternative Jellyfin client for my Android devices.
I used Jellyfix and the login works correctly on both, whereas with the official Jellyfin app it does not.

**Comment by Weedalf** [comment]
I had the same problem for years, and I finally found the solution yesterday.

In my case, IPv6 was disabled in my router, but the DynDNS update URL still contained an <ipv6addr> parameter.
Because of that, the DNS AAAA record was still being updated.

After removing the IPv6 parameter from the update URL in my router,
`dig jellyfin.mydomain.com AAAA +short`
still returned an IPv6 address.

Internally, this IPv6 address was reachable, but externally it was not —
and that was the reason why my external URL only worked inside my local network.

The official Jellyfin Android client has no IPv4 fallback when IPv6 fails.
Some alternative clients do have an IPv4 fallback, but not the official one.

My domain registrar does not allow me to delete the AAAA record, but I was able to edit it.
I set it to ::1, and after that, the IPv4 fallback started working.

However, my registrar (Strato) does not allow editing the AAAA record while DynDNS is active.
So I had to temporarily disable DynDNS, change the AAAA record to ::1, and then re-enable DynDNS.
After doing this, everything worked perfectly.

**Comment by nielsvanvelzen** [comment]
The networking library we use in the Android apps recently implemented Happy Eyeballs support so this IPv6 specific issue _should_ be fixed when we update it in the app (currently planned for 0.20).

**Comment by vuxuanhungg** [comment]
> Hello everyone, I think I've found the source of the connection problem, but I don't understand everything. The connection system is implemented by **OkHttp**. It seems that OkHttp is not compatible with TLS 1.3 on Android 9 and earlier versions. The **org.conscrypt:conscrypt-android** dependency would need to be added. [Link](https://stackoverflow.com/questions/55539513/how-to-enable-tlsv1-3-for-okhttp-3-12-x-on-android-8-9) I don't know how to code, so I can't suggest a change.
> 
> Maybe I should make a post for an improvement?
> 
> In the meantime, I launch the browser on the server address, connect quickly, and then cast from my phone. It seems faster than Kodi with the add-on.

I can confirm it only affects old Android versions. I test on 2 Android devices, 1 running Android 16 and the other running Android 8. Only the latter is stucked at the connect-to-server screen.
