### ISSUE TITLE
% symbol in episode title (metadata) crashes player

### ISSUE THREAD

**Issue by linetrimmer** [jellyfin/jellyfin-androidtv#365]
Just ran into this with the most recent Better Call Saul episode ‘50% Off’. 

Using either of the two built in players would crash the app (there were some bug reports sent), and using the external player would just stop the app with the show’s backdrop (i.e. never transferring to the external app).

I removed the % from the filename and the issue persisted. I then removed the % from the episode title metadata, making the title display in my library as ‘50 Off’, and the episode played immediately.

I honestly haven’t checked this with another file, but it was a pretty clear change from not working to working only after I took out the %

**Comment by AndreasGB** [comment]
Thanks for reporting, this is fixed in master.

You could either build the current master yourself or use the workaround of removing % from the title until the new version releases officially. Please feel free to re-open in case you still experience the problem on master or after the new version came out.

**Comment by AndreasGB** [comment]
A new Bugfix-Release is now out that fixes this problem
