### ISSUE TITLE
Subtitles out of sync after seeking

### ISSUE THREAD

**Issue by toxie** [jellyfin/jellyfin-androidtv#3909]
### Describe the bug

When playing ANY content and using subtitles when you manually seek forward or backwards the subtitles become out of sync with the video & audio by several seconds. The subtitles appear about 15-20seconds before the dialog actually happens on screen.
This only started to occur after this latest update.

### Application version

0.17.3

### Device information

Amazon Fire TV Stick 4k 1st gen

### Android version

Fire OS 6.7.0.5

### Jellyfin server version

10.9.9

**Comment by andries230** [comment]
This problem is not limited to the Android Client. I have this problem on all my Jellyfin clients (iOS, AndroidTV and Web).

However, on AndroidTV it is really annoying because the usual fix for this is to set **Subtitle Burn-in = Always**, which is currently not at all supported on the AndroidTV client.

**Comment by nielsvanvelzen** [comment]
These syncing issues should now be fixed with 0.18 as the subtitle code has been completely revamped.
