### ISSUE TITLE
Press back twice to exit Jellyfin application

### ISSUE THREAD

**Issue by SalmanMunawar** [jellyfin/jellyfin-androidtv#4333]
### Describe the feature you'd like

When on homepage/first page require the user to press back twice to exit the application. Currently on the homepage pressing back exit the application.

**Comment by nielsvanvelzen** [comment]
We don't have any reason to trap people in our app. If you are on the homepage without any previous page, pressing back will close the app. That's how Android is supposed to work.

**Comment by SalmanMunawar** [comment]
You aren’t trapping them, you are confirming exit, zidoo’s home theater application has similar behavior so user don’t accidentally exit the theater application while browsing movies.

**Comment by nielsvanvelzen** [comment]
Yes you are trapping a user because you deliberately make it harder to exit your app. This is a dark pattern used to keep users in an app to increase engagement (which advertisers love). The fact that a Chinese manufacturer that isn't even bothered to implement Android API's correctly does this in one of their app does not mean we should too.
