### ISSUE TITLE
Send Logs does nothing

### ISSUE THREAD

**Issue by thornbill** [jellyfin/jellyfin-androidtv#45]
The "Send Logs" option in the app does nothing since we removed the `LogReporter` in https://github.com/jellyfin/jellyfin-androidtv/pull/9. We should evaluate if there is a way to do this without depending on a centralized service. If not the UI for this should be removed.

**Comment by BnMcG** [comment]
I think if the button currently does nothing then it should be removed from the UI while a decision is made, otherwise it's just confusing and doesn't leave the user with a great impression. I can submit a PR for this if you like? It's been a while since I did any Android development, but I can probably manage that.

**Comment by thornbill** [comment]
I think removing the button until we work out an approach is a good idea.

**Comment by joshuaboniface** [comment]
Agreed, no sense keeping it around until it works.

**Comment by BnMcG** [comment]
I'll have a go at removing it shortly.

**Comment by thornbill** [comment]
[ACRA](https://github.com/ACRA/acra) looks like a potential solution for sending logs. We would just need to decide on a backend to use with it.
