### ISSUE TITLE
Directed by <unknown>

### ISSUE THREAD

**Issue by mahriman** [jellyfin/jellyfin-androidtv#479]
The androidtv-app seems to fail to display the director of a movie, possibly other fields as well.
I've confirmed that the director is shown as expected in the web client.

https://i.imgur.com/2P6rbYk.png

Jellyfin 10.5.4 / jellyfin-androidtv 0.11.3

**Comment by AndreasGB** [comment]
Hi there and thanks for the report!

In the upcoming redesign of the details screens we display the director along with the cast which I *think* might solve this problem for you. 

If you want to, you can build the `item-details-redesign` branch and check if it is fixed there, otherwise wait for the new release which will drop in the coming months.

**Comment by thornbill** [comment]
This needs verified, but I believe it may already be fixed on master.

**Comment by thornbill** [comment]
I can't find the PR that fixed this, but I am seeing the "Directed by" information populated now.

**Comment by dinacel** [comment]
I think there has been a regression — the director’s name no longer appears in v0.19.7.
