### ISSUE TITLE
[Feature Request] Android TV Home Screen Channel

### ISSUE THREAD

**Issue by buff0k** [jellyfin/jellyfin-androidtv#564]
I think it would be a good idea to implement a Home Screen Channel. I have been working through migrating my media server to Jellyfin due to my belief in Open Source Software and I do miss the convenience of starting my Next Up Episode / Movie from the Android TV Home Screen.

**Comment by thornbill** [comment]
Home screen channel integration was added in the 0.11.0 release of the app. What device are you using and what version of Android does it run? Our implementation currently only supports Android O or later.

**Comment by buff0k** [comment]
It's not showing up on my Customize Channels list? I am running Android 8.0 (Oreo) on a Xiaomi MiBox 3, the Emby Player did work so I assumed Jellyfin would too, suppose it's a unique bug.

**Comment by thornbill** [comment]
We probably don't share any bugs with Emby in the Android TV app, since the basis of our fork was their last open source version of the app from like 2017.

Content from Jellyfin should show up under the "Play Next" section. I believe @nielsvanvelzen mentioned that the controls for it do not display unless an app has additional home screen channels though.

**Comment by nielsvanvelzen** [comment]
Yup, it's a bug in Android but it was fixed after we added some additional channels. Should work in the next version!

**Comment by buff0k** [comment]
Thank you so very much. One of the key reasons I decided to move to Jellyfin, other than my commitment to Open Source Software is the active developer community.
