### ISSUE TITLE
Dear contributor,We love the UI of ios  jellyfin app and jellyfin Web browser UI

### ISSUE THREAD

**Issue by Yumega** [jellyfin/jellyfin-androidtv#565]
**Describe the feature you'd like**	
	
Dear contributor,We love the UI of ios jellyfin app and jellyfin Web browser UI, could you please set the jelly androidTV app into a same UI?  the current Adroid UI is unfriendly. 
**Additional context**

**Comment by HDmaniac** [comment]
This has been discussed on multiple occasions and reddit threads.

Quote from one of the devs:
_Android TV dev here. This is not likely to happen since most televisions have a slow processor which is unable to handle the webui. This is the same reason most TV's don't have a browser.

We know that the current app is ugly and buggy and are working hard to improve. Unfortunately that's hard with almost no contributors._

Check out [https://www.reddit.com/r/jellyfin/comments/inmt9e/please_allow_android_tv_to_use_the_web_ui/](url) for more discussion on the matter.
