### ISSUE TITLE
Can we use kotlin and/or some famous library on this project?

### ISSUE THREAD

**Issue by letroll** [jellyfin/jellyfin-androidtv#98]
do you have any reluctance to use kotlin? retrofit? a crash report library? The component architects of google? Or is it conceivable?

I'm not for library use for everything but some famous ones can simplify our life

**Comment by thornbill** [comment]
I have no general objection to Kotlin, but I don't think it would be worth adding unless it was included in some pretty major changes. I would be opposed to rewriting the existing code just to move to Kotlin as it would likely introduce issues without providing any real value.

We make use of a number of open source dependencies for the [app](https://github.com/jellyfin/jellyfin-androidtv/blob/master/app/build.gradle#L42-L53) and the apiclient library ([general](https://github.com/jellyfin/jellyfin-apiclient-java/blob/master/library/build.gradle#L5-L6) and [Android specific](https://github.com/jellyfin/jellyfin-apiclient-java/blob/master/android/build.gradle#L30)). These include Google's Gson, Volley, and Guava libraries, OkHttp and Picasso from Square, and ExoMedia a wrapper for Google's Exoplayer. We certainly are not opposed to using third party libraries here.

I have been looking at [ACRA](https://github.com/ACRA/acra) for error reporting to replace the custom solution that was removed from the app, but it will require a backend service to be setup to receive the logs. That will require some coordination to setup and get started, but I think is a worthwhile addition in the long term.

I am going to close this as there isn't a real issue here, but feel free to follow up with any additional questions or ask on [Riot or the forum](https://jellyfin.github.io/socialcontact.html).
